### ISSUE TITLE
FreshStandard.org is down 

### ISSUE THREAD

**Issue by GeorgeWL** [fresh-standard/FRESCA#25]
![](https://i.imgur.com/AVXcI9X.png)

**Comment by hacksalot** [comment]
Change of ownership, should be resolved shortly. Nice informative ICANN message though. Thanks for the report,.

**Comment by hacksalot** [comment]
New URL is https://resume.freshstandard.org, which will be reflected in the next release.

**Comment by Diti** [comment]
Dead link.
